server:
  port: 5001


spring:
  application:
    name: task-management

  h2:
    console:
      enabled: 'true'
  datasource:
    username: sa
    url: jdbc:h2:mem:task
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect


  kafka:
    listener:
      ack-mode: MANUAL_IMMEDIATE
    consumer:
#       bootstrap-servers: localhost:9092
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
      group-id: taskConsumer
      auto-offset-reset: earliest

      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer

      # handle retry on consumer
      enable-auto-commit: false
      max-poll-records: 100
      properties:
        max.poll.interval.ms: 60000
        retry.backoff.ms: 1000
        retry.max.attempts: 3
        retry.on.authentication.failure: true


microservices:
  taskCreation: http://localhost:9090/task-creation/api/v1/task/create
#   taskCreation: http://task-creation/api/v1/task/create
#   taskCreation: http://localhost:5000/api/v1/task/create

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka